server:
  port: 8085
  
spring:
  application:
    name: SyncService
    
  
  rabbitmq:
    host: ec2-3-128-80-159.us-east-2.compute.amazonaws.com
    port: 5672
    username: guest
    password: "TZnjbzV4x92TZ#"
    
    